name: MSIX Packaging

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  package-msix:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore NuGet packages
      run: dotnet restore D:\a\RPGGamer-Radio-Desktop\RPGGamer-Radio-Desktop\RPGGamer-Radio-Desktop.csproj

    - name: Build and Package MSIX
      run: msbuild D:\a\RPGGamer-Radio-Desktop\RPGGamer-Radio-Desktop\RPGGamer_Radio_Desktop.Publish\RPGGamer-Radio-Desktop.Publish.wapproj /p:Configuration=Release /p:AppxBundle=Always /p:UapAppxPackageBuildMode=StoreUpload
      working-directory: D:\a\RPGGamer-Radio-Desktop\RPGGamer-Radio-Desktop\RPGGamer_Radio_Desktop.Publish

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: MSIX Package Release ${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Upload MSIX Package
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: bin/Release/AppPackages/RPGGamer_Radio_Desktop_1.0.0.0_x64.msixbundle
        asset_name: RPGGamer_Radio_Desktop_1.0.0.0_x64.msixbundle
        asset_content_type: application/vnd.ms-appx.bundle
